import { Copy } from "lucide-react";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

interface AutoGeneratedCodeFieldProps {
  code: string;
  label: string;
  onCopy: () => void;
  copyAriaLabel: string;
}

export function AutoGeneratedCodeField({
  code,
  label,
  onCopy,
  copyAriaLabel,
}: AutoGeneratedCodeFieldProps) {
  return (
    <div className="space-y-2">
      <Label>{label}</Label>
      <div className="flex items-center gap-2">
        <Input value={code} readOnly className="font-mono tracking-wider" />
        <Button
          type="button"
          variant="outline"
          size="icon"
          onClick={onCopy}
          aria-label={copyAriaLabel}
        >
          <Copy className="h-4 w-4" />
        </Button>
      </div>
      <p className="text-xs text-muted-foreground">
        Auto-generated on create. Not editable.
      </p>
    </div>
  );
}
