import { Controller, useWatch, type Control, type FieldErrors } from "react-hook-form";

import {
  PLAN_BILLING_PERIODS,
  billingPeriodLabels,
  type PlanFormValues,
} from "@/schemas/plan.schema";
import { deriveAnnualPricing } from "@/lib/plans/plan-form.utils";
import { AutoGeneratedCodeField } from "@/components/plans/AutoGeneratedCodeField";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";

interface PlanFormDetailsCardProps {
  control: Control<PlanFormValues>;
  errors: FieldErrors<PlanFormValues>;
  isEditMode: boolean;
  planCode?: string;
  onCopyCode: () => void;
  isCustomPricing: boolean;
}

export function PlanFormDetailsCard({
  control,
  errors,
  isEditMode,
  planCode,
  onCopyCode,
  isCustomPricing,
}: PlanFormDetailsCardProps) {
  const monthlyPrice = useWatch({ control, name: "price" });
  const annualPrice = useWatch({ control, name: "annualPrice" });
  const annualPricing = deriveAnnualPricing(monthlyPrice, annualPrice);

  return (
    <Card>
      <CardHeader>
        <CardTitle>{isEditMode ? "Edit Plan" : "Create Plan"}</CardTitle>
        <CardDescription>
          Configure a subscription tier for the pricing page.
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        {isEditMode && planCode ? (
          <AutoGeneratedCodeField
            code={planCode}
            label="Plan code"
            onCopy={onCopyCode}
            copyAriaLabel="Copy plan code"
          />
        ) : null}

        <div className="grid gap-4 md:grid-cols-3">
          <div className="space-y-2">
            <Label htmlFor="nameEn">Name (EN)</Label>
            <Controller
              name="nameEn"
              control={control}
              render={({ field }) => <Input id="nameEn" {...field} />}
            />
            {errors.nameEn ? (
              <p className="text-xs text-destructive">{errors.nameEn.message}</p>
            ) : null}
          </div>
          <div className="space-y-2">
            <Label htmlFor="nameMm">Name (MM)</Label>
            <Controller
              name="nameMm"
              control={control}
              render={({ field }) => <Input id="nameMm" {...field} />}
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="nameTh">Name (TH)</Label>
            <Controller
              name="nameTh"
              control={control}
              render={({ field }) => <Input id="nameTh" {...field} />}
            />
          </div>
        </div>

        <div className="space-y-2">
          <Label htmlFor="descriptionEn">Description (EN)</Label>
          <Controller
            name="descriptionEn"
            control={control}
            render={({ field }) => (
              <Textarea id="descriptionEn" rows={3} {...field} />
            )}
          />
        </div>

        <div className="grid gap-4 md:grid-cols-2">
          <div className="space-y-2">
            <Label htmlFor="ctaLabel">CTA label</Label>
            <Controller
              name="ctaLabel"
              control={control}
              render={({ field }) => (
                <Input id="ctaLabel" placeholder="GET STARTED" {...field} />
              )}
            />
          </div>
          <div className="space-y-2">
            <Label>Default billing period</Label>
            <Controller
              name="billingPeriod"
              control={control}
              render={({ field }) => (
                <Select value={field.value} onValueChange={field.onChange}>
                  <SelectTrigger hideClear>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {PLAN_BILLING_PERIODS.map((period) => (
                      <SelectItem key={period} value={period}>
                        {billingPeriodLabels[period]}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              )}
            />
            <p className="text-xs text-muted-foreground">
              Which tab the pricing page opens on. Both prices stay available in
              the Monthly / Annually toggle.
            </p>
          </div>
        </div>

        <div className="flex flex-wrap gap-6">
          <Controller
            name="isCustomPricing"
            control={control}
            render={({ field }) => (
              <div className="flex items-center gap-2">
                <Switch checked={field.value} onCheckedChange={field.onChange} />
                <Label>Custom pricing (&quot;Let&apos;s talk&quot;)</Label>
              </div>
            )}
          />
          <Controller
            name="isPopular"
            control={control}
            render={({ field }) => (
              <div className="flex items-center gap-2">
                <Switch checked={field.value} onCheckedChange={field.onChange} />
                <Label>Most popular badge</Label>
              </div>
            )}
          />
          <Controller
            name="isActive"
            control={control}
            render={({ field }) => (
              <div className="flex items-center gap-2">
                <Switch checked={field.value} onCheckedChange={field.onChange} />
                <Label>Active</Label>
              </div>
            )}
          />
        </div>

        {!isCustomPricing ? (
          <div className="grid gap-4 md:grid-cols-2">
            <div className="space-y-2">
              <Label htmlFor="price">Monthly price (฿ / month)</Label>
              <Controller
                name="price"
                control={control}
                render={({ field }) => (
                  <Input
                    id="price"
                    type="number"
                    min={0}
                    step={1}
                    value={field.value ?? ""}
                    onChange={(e) => {
                      const next = e.target.value;
                      field.onChange(next === "" ? undefined : Number(next));
                    }}
                  />
                )}
              />
              <p className="text-xs text-muted-foreground">
                Charged every month when the customer picks “Monthly”.
              </p>
              {errors.price ? (
                <p className="text-xs text-destructive">
                  {errors.price.message}
                </p>
              ) : null}
            </div>

            <div className="space-y-2">
              <Label htmlFor="annualPrice">Annual price (฿ / year)</Label>
              <Controller
                name="annualPrice"
                control={control}
                render={({ field }) => (
                  <Input
                    id="annualPrice"
                    type="number"
                    min={0}
                    step={1}
                    placeholder="Leave empty for no annual option"
                    value={field.value ?? ""}
                    onChange={(e) => {
                      const next = e.target.value;
                      field.onChange(next === "" ? undefined : Number(next));
                    }}
                  />
                )}
              />
              <p className="text-xs text-muted-foreground">
                {annualPricing
                  ? `Shows as ฿${annualPricing.monthlyEquivalent.toLocaleString()} / mo, billed annually${
                      annualPricing.discountPercent != null
                        ? ` · Save ${annualPricing.discountPercent}%`
                        : ""
                    }`
                  : "Total charged once per year. Leave empty to hide the “Annually” option for this plan."}
              </p>
              {errors.annualPrice ? (
                <p className="text-xs text-destructive">
                  {errors.annualPrice.message}
                </p>
              ) : null}
            </div>
          </div>
        ) : null}
      </CardContent>
    </Card>
  );
}
