import {
  Controller,
  type Control,
  type FieldArrayWithId,
  type FieldErrors,
} from "react-hook-form";
import { Plus, Trash2 } from "lucide-react";

import {
  DISPLAY_ONLY_FEATURE_KEY,
  type PlanFeatureFormValues,
} from "@/schemas/plan-feature.schema";
import type {
  PlanFeatureKeyInfo,
  PlanFeatureKeyOption,
  PlanFeatureValueType,
} from "@/services/planService";
import { AutoGeneratedCodeField } from "@/components/plans/AutoGeneratedCodeField";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";

/** What the admin has to fill in on the plan once this capability is linked. */
const VALUE_TYPE_HINT: Record<PlanFeatureValueType, string> = {
  COUNT:
    'Plans set a number ("Quantity"), or switch on Unlimited. Use "Period" for per-day limits.',
  LEVEL: 'Plans set a grade in "Value label" — e.g. Basic / Mid / Super.',
  SELECTION:
    'Plans tick which of the package options below they offer, then set "Choose how many".',
};

interface PlanFeatureFormCardProps {
  control: Control<PlanFeatureFormValues>;
  errors: FieldErrors<PlanFeatureFormValues>;
  isEditMode: boolean;
  featureCode?: string;
  onCopyCode: () => void;
  keyOptions: PlanFeatureKeyOption[];
  /** Id of the feature being edited, so it does not read as "taken by itself". */
  currentFeatureId?: number;
  /** The edited feature's own capability, so the label shows before keyOptions load. */
  currentFeatureKeyInfo?: PlanFeatureKeyInfo | null;
  optionFields: FieldArrayWithId<PlanFeatureFormValues, "options", "id">[];
  onAddOption: () => void;
  onRemoveOption: (index: number) => void;
}

export function PlanFeatureFormCard({
  control,
  errors,
  isEditMode,
  featureCode,
  onCopyCode,
  keyOptions,
  currentFeatureId,
  currentFeatureKeyInfo,
  optionFields,
  onAddOption,
  onRemoveOption,
}: PlanFeatureFormCardProps) {
  /**
   * Resolves what to show for a capability value. Driven by the Controller's own
   * `field.value` rather than a separate useWatch subscription, so the label can
   * never disagree with what would be submitted. Falls back to the edited
   * feature's own info because the capability list can still be in flight when
   * the saved value reaches the form.
   */
  const describeKey = (rawValue: string | undefined) => {
    const isDisplayOnly = !rawValue || rawValue === DISPLAY_ONLY_FEATURE_KEY;
    const info: PlanFeatureKeyInfo | null = isDisplayOnly
      ? null
      : (keyOptions.find((item) => item.key === rawValue) ??
        (currentFeatureKeyInfo?.key === rawValue
          ? currentFeatureKeyInfo
          : null));
    return {
      isDisplayOnly,
      info,
      label: isDisplayOnly
        ? "Display only — nothing to enforce"
        : (info?.label ?? rawValue!),
    };
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle>
          {isEditMode ? "Edit Plan Feature" : "Create Plan Feature"}
        </CardTitle>
        <CardDescription>
          A reusable feature row such as Boosting or Flash Drop.
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        {isEditMode && featureCode ? (
          <AutoGeneratedCodeField
            code={featureCode}
            label="Feature code"
            onCopy={onCopyCode}
            copyAriaLabel="Copy feature code"
          />
        ) : null}

        <div className="grid gap-4 md:grid-cols-3">
          <div className="space-y-2">
            <Label htmlFor="nameEn">Name (EN)</Label>
            <Controller
              name="nameEn"
              control={control}
              render={({ field }) => <Input id="nameEn" {...field} />}
            />
            {errors.nameEn ? (
              <p className="text-xs text-destructive">{errors.nameEn.message}</p>
            ) : null}
          </div>
          <div className="space-y-2">
            <Label htmlFor="nameMm">Name (MM)</Label>
            <Controller
              name="nameMm"
              control={control}
              render={({ field }) => <Input id="nameMm" {...field} />}
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="nameTh">Name (TH)</Label>
            <Controller
              name="nameTh"
              control={control}
              render={({ field }) => <Input id="nameTh" {...field} />}
            />
          </div>
        </div>

        <div className="space-y-2 rounded-lg border p-4">
          <Label htmlFor="featureKey">Linked capability</Label>
          <Controller
            name="featureKey"
            control={control}
            render={({ field }) => {
              const selected = describeKey(field.value);
              return (
                <>
                  <Select
                    value={field.value || DISPLAY_ONLY_FEATURE_KEY}
                    onValueChange={field.onChange}
                  >
                    {/* hideClear: clearing would set an invalid "" — "Display
                        only" is this field's empty state. */}
                    <SelectTrigger id="featureKey" hideClear>
                      {/* Rendered explicitly: Radix leaves the trigger blank when
                          the value is set before its item has mounted. */}
                      <SelectValue>{selected.label}</SelectValue>
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value={DISPLAY_ONLY_FEATURE_KEY}>
                        Display only — nothing to enforce
                      </SelectItem>
                      {keyOptions.map((option) => {
                        const takenByOther =
                          option.usedByFeatureId != null &&
                          option.usedByFeatureId !== currentFeatureId;
                        return (
                          <SelectItem
                            key={option.key}
                            value={option.key}
                            disabled={takenByOther}
                          >
                            {option.label}
                            {takenByOther
                              ? ` — already used by "${option.usedByFeatureName}"`
                              : ""}
                          </SelectItem>
                        );
                      })}
                    </SelectContent>
                  </Select>

                  {selected.info ? (
                    <div className="space-y-2 pt-1">
                      <div className="flex flex-wrap items-center gap-2">
                        <Badge variant="secondary">
                          {selected.info.valueType}
                        </Badge>
                        <code className="rounded bg-muted px-1.5 py-0.5 text-xs">
                          {selected.info.key}
                        </code>
                      </div>
                      <p className="text-xs text-muted-foreground">
                        {selected.info.description}
                      </p>
                      <p className="text-xs text-muted-foreground">
                        {VALUE_TYPE_HINT[selected.info.valueType]}
                      </p>
                    </div>
                  ) : selected.isDisplayOnly ? (
                    <p className="pt-1 text-xs text-muted-foreground">
                      This feature will show on the pricing page but the app will
                      not check it — right for marketing rows such as &quot;No
                      Ads&quot; or &quot;Website (QR) for shop menu&quot;. Pick a
                      capability when the quota has to be enforced later.
                    </p>
                  ) : null}
                </>
              );
            }}
          />
        </div>

        <div className="space-y-2">
          <Label htmlFor="descriptionEn">Tooltip (EN)</Label>
          <Controller
            name="descriptionEn"
            control={control}
            render={({ field }) => (
              <Textarea
                id="descriptionEn"
                rows={2}
                placeholder="Push notifications sent to local users about sudden discounts."
                {...field}
              />
            )}
          />
          <p className="text-xs text-muted-foreground">
            Shown when a visitor hovers the feature name on the pricing page.
          </p>
        </div>

        <div className="space-y-3 rounded-lg border p-4">
          <div className="flex items-start justify-between gap-4">
            <div>
              <Label>Package options</Label>
              <p className="text-xs text-muted-foreground">
                Only for &quot;pick N of these&quot; features such as the Social
                Media package. Each plan then decides how many of these a shop may
                choose.
              </p>
            </div>
            <Button
              type="button"
              variant="outline"
              size="sm"
              onClick={onAddOption}
            >
              <Plus className="mr-2 h-4 w-4" />
              Add option
            </Button>
          </div>

          {optionFields.length === 0 ? (
            <p className="text-sm text-muted-foreground">
              No options — this feature is a plain quota row.
            </p>
          ) : (
            <div className="space-y-2">
              {optionFields.map((field, index) => (
                <div key={field.id} className="flex items-start gap-2">
                  <div className="flex-1 space-y-1">
                    <Controller
                      name={`options.${index}.textEn`}
                      control={control}
                      render={({ field: textField }) => (
                        <Input
                          placeholder="Facebook post x 2"
                          {...textField}
                        />
                      )}
                    />
                    {errors.options?.[index]?.textEn ? (
                      <p className="text-xs text-destructive">
                        {errors.options[index]?.textEn?.message}
                      </p>
                    ) : null}
                  </div>
                  <Button
                    type="button"
                    variant="ghost"
                    size="icon"
                    className="h-9 w-9 shrink-0"
                    aria-label={`Remove option ${index + 1}`}
                    onClick={() => onRemoveOption(index)}
                  >
                    <Trash2 className="h-4 w-4" />
                  </Button>
                </div>
              ))}
            </div>
          )}
        </div>

        <Controller
          name="isActive"
          control={control}
          render={({ field }) => (
            <div className="flex items-center gap-2">
              <Switch checked={field.value} onCheckedChange={field.onChange} />
              <Label>Active</Label>
            </div>
          )}
        />
      </CardContent>
    </Card>
  );
}
