import { Controller, type Control, type FieldErrors } from "react-hook-form";

import type { PlanFeatureFormValues } from "@/schemas/plan-feature.schema";
import { AutoGeneratedCodeField } from "@/components/plans/AutoGeneratedCodeField";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";

interface PlanFeatureFormCardProps {
  control: Control<PlanFeatureFormValues>;
  errors: FieldErrors<PlanFeatureFormValues>;
  isEditMode: boolean;
  featureCode?: string;
  onCopyCode: () => void;
}

export function PlanFeatureFormCard({
  control,
  errors,
  isEditMode,
  featureCode,
  onCopyCode,
}: PlanFeatureFormCardProps) {
  return (
    <Card>
      <CardHeader>
        <CardTitle>
          {isEditMode ? "Edit Plan Feature" : "Create Plan Feature"}
        </CardTitle>
        <CardDescription>
          A reusable feature row such as Boosting or Flash Drop.
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        {isEditMode && featureCode ? (
          <AutoGeneratedCodeField
            code={featureCode}
            label="Feature code"
            onCopy={onCopyCode}
            copyAriaLabel="Copy feature code"
          />
        ) : null}

        <div className="grid gap-4 md:grid-cols-3">
          <div className="space-y-2">
            <Label htmlFor="nameEn">Name (EN)</Label>
            <Controller
              name="nameEn"
              control={control}
              render={({ field }) => <Input id="nameEn" {...field} />}
            />
            {errors.nameEn ? (
              <p className="text-xs text-destructive">{errors.nameEn.message}</p>
            ) : null}
          </div>
          <div className="space-y-2">
            <Label htmlFor="nameMm">Name (MM)</Label>
            <Controller
              name="nameMm"
              control={control}
              render={({ field }) => <Input id="nameMm" {...field} />}
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="nameTh">Name (TH)</Label>
            <Controller
              name="nameTh"
              control={control}
              render={({ field }) => <Input id="nameTh" {...field} />}
            />
          </div>
        </div>

        <Controller
          name="isActive"
          control={control}
          render={({ field }) => (
            <div className="flex items-center gap-2">
              <Switch checked={field.value} onCheckedChange={field.onChange} />
              <Label>Active</Label>
            </div>
          )}
        />
      </CardContent>
    </Card>
  );
}
